# Prometheus configuration for RAG Assistant monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rag-assistant-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # RAG Assistant application metrics
  - job_name: 'rag-assistant'
    static_configs:
      - targets: ['rag-assistant:8000']  # Metrics endpoint
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    params:
      format: ['prometheus']

  # System metrics (if node_exporter is available)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Docker container metrics (if cadvisor is available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx metrics (if nginx-prometheus-exporter is available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 10s

  # ChromaDB metrics (if exposed)
  - job_name: 'chromadb'
    static_configs:
      - targets: ['chromadb:8000']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /api/v1/heartbeat